#GENERATED BY GEMINI 3.1 PRO

import redis
import json
import numpy as np
import matplotlib.pyplot as plt

def main():
    # 1. Connect to your EC2 Redis Broker
    r = redis.Redis(
        host='<YOUR_EC2_PUBLIC_IP>', # Your EC2 Public IP
        port=6379,
        decode_responses=True
    )

    # 2. Setup the empty matrix and tracking variables
    size_n = 100
    total_jobs = 10
    rows_per_worker = size_n // total_jobs
    final_matrix = np.zeros((size_n, size_n))
    chunks_received = 0

    # 3. Subscribe to the channel
    pubsub = r.pubsub()
    pubsub.subscribe('wave_channel')

    print("Listening for wave data from EKS cluster...")

    # 4. Listen for incoming data
    for message in pubsub.listen():
        if message['type'] == 'message':
            # Parse the JSON payload
            payload = json.loads(message['data'])
            job_index = payload['job_index']
            chunk_data = np.array(payload['chunk_data'])
            
            # Calculate where this chunk belongs
            start_row = job_index * rows_per_worker
            end_row = start_row + rows_per_worker
            
            # Insert the chunk into the final matrix
            final_matrix[start_row:end_row, :] = chunk_data
            chunks_received += 1
            
            print(f"Received chunk {job_index + 1}/10 from Job Index {job_index}")
            
            # Once all 10 chunks arrive, plot the matrix and break the loop
            if chunks_received == total_jobs:
                print("All chunks received! Rendering wave matrix...")
                plt.imshow(final_matrix, cmap='viridis')
                plt.colorbar(label='Wave Amplitude')
                plt.title('Quantum Wave Function Matrix')
                plt.show()
                break

if __name__ == "__main__":
    main()